project:
  type: book
  output-dir: _site

book:
  title: "rstatsZH"
  subtitle: "Data Science mit R"
  author: "Lars Schöbitz"
  date: today
  chapters:
    - index.qmd
    - module.qmd
    - kurse.qmd
    - projekte.qmd
    - references.qmd

bibliography: rstatszh.bib

format:
  html:
    theme:
      light: [litera, theme.scss]
    link-external-icon: true
    link-external-newwindow: true
    highlight-style: a11y-dark
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
    mainfont: "Atkinson Hyperlegible"
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    include-in-header: 
        - text: |
            <script defer data-domain="rstats.zuerich" src="https://plausible.io/js/script.js"></script>

execute:
    freeze: auto
    echo: false
    message: false
    warning: false