project:
  type: book

book:
  title: "rstatsZH"
  author: "Lars Schöbitz"
  date: today
  chapters:
    - index.qmd
    - module.qmd
    - kurse.qmd
    - references.qmd

bibliography: rstatszh.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex

execute:
    freeze: auto
    echo: false
    message: false
    warning: false