---
execute:
    eval: true
---

```{r}
#| echo: false
#| include: false
Sys.setlocale("LC_TIME", "de_DE.UTF-8")
options(knitr.kable.NA = '')
```

# Abschlussprojekt {#sec-projekte}

Das Abschlussprojekt ist ein fester Bestandteil des Kurses. Es umfasst einen Bericht zu einer Datenanalyse mit von den Teilnehmer:innen gewählten Daten. Das Projekt wird im Zeitraum des Kurses erstellt und begleitet. Für die gewählten Daten kommen bereits als OGD veröffentlichte Daten in Frage oder eigene Daten, welche als OGD veröffentlicht werden. Der Code für den Bericht ist von Beginn an über GitHub öffentlich publiziert und der Bericht selbst mittels GitHub Pages in einem für die Öffentlichkeit nützlichem Format geteilt. Somit werden im Abschlussprojekt nicht nur die im Kurs gelernten Fähigkeiten für R geübt, sondern auch "open source" gearbeitet mit Werkzeugen, die eine öffentliche Verwaltung unterstüten.

## Projekte

Die folgende Tabelle zeigt einen Überblick über die im Kurs entstandenen Projekte. Jedes Projekt hat eine eigenständige Webseite. Die Tabelle zeigt die folgenden Variablen:

- vorname: Vorname Kursteilnehmer:in
- nachname: Nachname Kursteilnehmer:in
- gh_username: GitHub Benutzername mit verlinktem GitHub Profil
- abteilung: 
- kurs: Titel des Kurses 
- daten: Titel des Datensatzes
- daten_ogd: Angabe ob Daten bereits als OGD publiziert wurden
- daten_url: Angabe der URL des publizierten Datensatzes
- ...

